---
# tasks file for enqack.confluence

- name: Add daemon
  template:
    src: "{{ role_path }}/templates/confluence.service.j2"
    dest: "/etc/systemd/system/confluence.service"
    owner: "{{ confluence_run_user }}"
    group: "{{ confluence_run_group }}"
    mode: 0664

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Enable and start daemon
  systemd:
    name: confluence.service
    enabled: true
    state: restarted
